service: cmm-put

provider:
  name: aws
  stage: dev2
  runtime: python3.8
  region: eu-west-1
  timeout: 40

package:
  artifact: package.zip

functions:
  job:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: cmm-filtered
          event: s3:ObjectCreated:*
          rules:
            - suffix: .ACTL
          existing: true
    tags:
      project: cmm
